changelog:
  categories:
    - title: Features
      labels:
        - "*"
      exclude:
        labels:
          - bug
          - renovate
          - dependabot
    - title: Bugs fixed
      labels:
        - bug
    - title: Dependencies
      labels:
        - renovate
        - dependabot
